[build]
  # This is a Node.js Express server, not a Next.js app
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

# Serve the main page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"